esHost: localhost:9200, localhost:9201

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true